// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.example.diagassistant.telemetry;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:telemetry.Empty)
    com.google.protobuf.MessageOrBuilder {
}
