// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.example.diagassistant.telemetry;

public interface TelemetrySampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:telemetry.TelemetrySample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rpm = 1;</code>
   * @return The rpm.
   */
  int getRpm();

  /**
   * <code>float temperature_c = 2;</code>
   * @return The temperatureC.
   */
  float getTemperatureC();

  /**
   * <code>uint32 adc_raw = 3;</code>
   * @return The adcRaw.
   */
  int getAdcRaw();

  /**
   * <code>int64 ts_ms = 4;</code>
   * @return The tsMs.
   */
  long getTsMs();
}
