// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.example.diagassistant.telemetry;

public final class Telemetry {
  private Telemetry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_telemetry_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_telemetry_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_telemetry_TelemetrySample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_telemetry_TelemetrySample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017telemetry.proto\022\ttelemetry\"\007\n\005Empty\"U\n" +
      "\017TelemetrySample\022\013\n\003rpm\030\001 \001(\005\022\025\n\rtempera" +
      "ture_c\030\002 \001(\002\022\017\n\007adc_raw\030\003 \001(\r\022\r\n\005ts_ms\030\004" +
      " \001(\0032U\n\020TelemetryService\022A\n\017StreamTeleme" +
      "try\022\020.telemetry.Empty\032\032.telemetry.Teleme" +
      "trySample0\001B\'\n#com.example.diagassistant" +
      ".telemetryP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_telemetry_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_telemetry_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_telemetry_Empty_descriptor,
        new String[] { });
    internal_static_telemetry_TelemetrySample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_telemetry_TelemetrySample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_telemetry_TelemetrySample_descriptor,
        new String[] { "Rpm", "TemperatureC", "AdcRaw", "TsMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
