// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.example.diagassistant.telemetry;

/**
 * Protobuf type {@code telemetry.TelemetrySample}
 */
public final class TelemetrySample extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:telemetry.TelemetrySample)
    TelemetrySampleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TelemetrySample.newBuilder() to construct.
  private TelemetrySample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TelemetrySample() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TelemetrySample();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Telemetry.internal_static_telemetry_TelemetrySample_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Telemetry.internal_static_telemetry_TelemetrySample_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TelemetrySample.class, Builder.class);
  }

  public static final int RPM_FIELD_NUMBER = 1;
  private int rpm_;
  /**
   * <code>int32 rpm = 1;</code>
   * @return The rpm.
   */
  @Override
  public int getRpm() {
    return rpm_;
  }

  public static final int TEMPERATURE_C_FIELD_NUMBER = 2;
  private float temperatureC_;
  /**
   * <code>float temperature_c = 2;</code>
   * @return The temperatureC.
   */
  @Override
  public float getTemperatureC() {
    return temperatureC_;
  }

  public static final int ADC_RAW_FIELD_NUMBER = 3;
  private int adcRaw_;
  /**
   * <code>uint32 adc_raw = 3;</code>
   * @return The adcRaw.
   */
  @Override
  public int getAdcRaw() {
    return adcRaw_;
  }

  public static final int TS_MS_FIELD_NUMBER = 4;
  private long tsMs_;
  /**
   * <code>int64 ts_ms = 4;</code>
   * @return The tsMs.
   */
  @Override
  public long getTsMs() {
    return tsMs_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rpm_ != 0) {
      output.writeInt32(1, rpm_);
    }
    if (Float.floatToRawIntBits(temperatureC_) != 0) {
      output.writeFloat(2, temperatureC_);
    }
    if (adcRaw_ != 0) {
      output.writeUInt32(3, adcRaw_);
    }
    if (tsMs_ != 0L) {
      output.writeInt64(4, tsMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rpm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rpm_);
    }
    if (Float.floatToRawIntBits(temperatureC_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, temperatureC_);
    }
    if (adcRaw_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, adcRaw_);
    }
    if (tsMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, tsMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TelemetrySample)) {
      return super.equals(obj);
    }
    TelemetrySample other = (TelemetrySample) obj;

    if (getRpm()
        != other.getRpm()) return false;
    if (Float.floatToIntBits(getTemperatureC())
        != Float.floatToIntBits(
            other.getTemperatureC())) return false;
    if (getAdcRaw()
        != other.getAdcRaw()) return false;
    if (getTsMs()
        != other.getTsMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RPM_FIELD_NUMBER;
    hash = (53 * hash) + getRpm();
    hash = (37 * hash) + TEMPERATURE_C_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getTemperatureC());
    hash = (37 * hash) + ADC_RAW_FIELD_NUMBER;
    hash = (53 * hash) + getAdcRaw();
    hash = (37 * hash) + TS_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTsMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TelemetrySample parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TelemetrySample parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TelemetrySample parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TelemetrySample parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TelemetrySample parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TelemetrySample parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TelemetrySample parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TelemetrySample parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TelemetrySample parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TelemetrySample parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TelemetrySample parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TelemetrySample parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TelemetrySample prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code telemetry.TelemetrySample}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:telemetry.TelemetrySample)
      TelemetrySampleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Telemetry.internal_static_telemetry_TelemetrySample_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Telemetry.internal_static_telemetry_TelemetrySample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TelemetrySample.class, Builder.class);
    }

    // Construct using com.example.diagassistant.telemetry.TelemetrySample.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      rpm_ = 0;

      temperatureC_ = 0F;

      adcRaw_ = 0;

      tsMs_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Telemetry.internal_static_telemetry_TelemetrySample_descriptor;
    }

    @Override
    public TelemetrySample getDefaultInstanceForType() {
      return TelemetrySample.getDefaultInstance();
    }

    @Override
    public TelemetrySample build() {
      TelemetrySample result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TelemetrySample buildPartial() {
      TelemetrySample result = new TelemetrySample(this);
      result.rpm_ = rpm_;
      result.temperatureC_ = temperatureC_;
      result.adcRaw_ = adcRaw_;
      result.tsMs_ = tsMs_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TelemetrySample) {
        return mergeFrom((TelemetrySample)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TelemetrySample other) {
      if (other == TelemetrySample.getDefaultInstance()) return this;
      if (other.getRpm() != 0) {
        setRpm(other.getRpm());
      }
      if (other.getTemperatureC() != 0F) {
        setTemperatureC(other.getTemperatureC());
      }
      if (other.getAdcRaw() != 0) {
        setAdcRaw(other.getAdcRaw());
      }
      if (other.getTsMs() != 0L) {
        setTsMs(other.getTsMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              rpm_ = input.readInt32();

              break;
            } // case 8
            case 21: {
              temperatureC_ = input.readFloat();

              break;
            } // case 21
            case 24: {
              adcRaw_ = input.readUInt32();

              break;
            } // case 24
            case 32: {
              tsMs_ = input.readInt64();

              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int rpm_ ;
    /**
     * <code>int32 rpm = 1;</code>
     * @return The rpm.
     */
    @Override
    public int getRpm() {
      return rpm_;
    }
    /**
     * <code>int32 rpm = 1;</code>
     * @param value The rpm to set.
     * @return This builder for chaining.
     */
    public Builder setRpm(int value) {
      
      rpm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rpm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRpm() {
      
      rpm_ = 0;
      onChanged();
      return this;
    }

    private float temperatureC_ ;
    /**
     * <code>float temperature_c = 2;</code>
     * @return The temperatureC.
     */
    @Override
    public float getTemperatureC() {
      return temperatureC_;
    }
    /**
     * <code>float temperature_c = 2;</code>
     * @param value The temperatureC to set.
     * @return This builder for chaining.
     */
    public Builder setTemperatureC(float value) {
      
      temperatureC_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature_c = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperatureC() {
      
      temperatureC_ = 0F;
      onChanged();
      return this;
    }

    private int adcRaw_ ;
    /**
     * <code>uint32 adc_raw = 3;</code>
     * @return The adcRaw.
     */
    @Override
    public int getAdcRaw() {
      return adcRaw_;
    }
    /**
     * <code>uint32 adc_raw = 3;</code>
     * @param value The adcRaw to set.
     * @return This builder for chaining.
     */
    public Builder setAdcRaw(int value) {
      
      adcRaw_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 adc_raw = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdcRaw() {
      
      adcRaw_ = 0;
      onChanged();
      return this;
    }

    private long tsMs_ ;
    /**
     * <code>int64 ts_ms = 4;</code>
     * @return The tsMs.
     */
    @Override
    public long getTsMs() {
      return tsMs_;
    }
    /**
     * <code>int64 ts_ms = 4;</code>
     * @param value The tsMs to set.
     * @return This builder for chaining.
     */
    public Builder setTsMs(long value) {
      
      tsMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ts_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTsMs() {
      
      tsMs_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:telemetry.TelemetrySample)
  }

  // @@protoc_insertion_point(class_scope:telemetry.TelemetrySample)
  private static final TelemetrySample DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TelemetrySample();
  }

  public static TelemetrySample getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TelemetrySample>
      PARSER = new com.google.protobuf.AbstractParser<TelemetrySample>() {
    @Override
    public TelemetrySample parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TelemetrySample> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TelemetrySample> getParserForType() {
    return PARSER;
  }

  @Override
  public TelemetrySample getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

